# Reference: https://github.com/i3/i3/blob/next/etc/config

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]
ctrl-enter = 'exec-and-forget open -n /Applications/iTerm.app'
ctrl-shift-enter = 'exec-and-forget open -n /Applications/Safari.app'

ctrl-left = 'focus left'
ctrl-down = 'focus down'
ctrl-up = 'focus up'
ctrl-right = 'focus right'

ctrl-shift-left = 'move left'
ctrl-shift-down = 'move down'
ctrl-shift-up = 'move up'
ctrl-shift-right = 'move right'

# Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
# ctrl-h = 'split horizontal'
# ctrl-v = 'split vertical'

ctrl-shift-f = 'fullscreen'

ctrl-shift-s = 'layout v_accordion' # 'layout stacking' in i3
ctrl-shift-w = 'layout h_accordion' # 'layout tabbed' in i3
ctrl-shift-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

ctrl-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#ctrl-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# ctrl-a = 'focus parent'

ctrl-1 = 'workspace --auto-back-and-forth 1'
ctrl-2 = 'workspace --auto-back-and-forth 2'
ctrl-3 = 'workspace --auto-back-and-forth 3'
ctrl-4 = 'workspace --auto-back-and-forth 4'
ctrl-5 = 'workspace --auto-back-and-forth 5'
ctrl-6 = 'workspace --auto-back-and-forth 6'
ctrl-7 = 'workspace --auto-back-and-forth 7'
ctrl-8 = 'workspace --auto-back-and-forth 8'
ctrl-9 = 'workspace --auto-back-and-forth 9'
ctrl-0 = 'workspace --auto-back-and-forth 10'

ctrl-shift-1 = 'move-node-to-workspace 1'
ctrl-shift-2 = 'move-node-to-workspace 2'
ctrl-shift-3 = 'move-node-to-workspace 3'
ctrl-shift-4 = 'move-node-to-workspace 4'
ctrl-shift-5 = 'move-node-to-workspace 5'
ctrl-shift-6 = 'move-node-to-workspace 6'
ctrl-shift-7 = 'move-node-to-workspace 7'
ctrl-shift-8 = 'move-node-to-workspace 8'
ctrl-shift-9 = 'move-node-to-workspace 9'
ctrl-shift-0 = 'move-node-to-workspace 10'

ctrl-shift-c = 'reload-config'

ctrl-shift-r = 'mode resize'

[mode.resize.binding]
left = 'resize width -50'
up = 'resize height +50'
down = 'resize height -50'
right = 'resize width +50'
enter = 'mode main'
esc = 'mode main'
